### ISSUE TITLE
paper publish

### ISSUE THREAD

**Issue by Aithusa1113** [ZhengyuLiang24/LF-AFnet#1]
Hi, may I ask have your paper publised yet and where can I get your paper (LF-AFnet)? 

Thanks.

**Comment by ZhengyuLiang24** [comment]
> Hi, may I ask have your paper publised yet and where can I get your paper (LF-AFnet)?
> 
> Thanks.

Thanks for your attention. The paper is now in the peer review stage, and we will publish it as soon as possible.

**Comment by Aithusa1113** [comment]
Thanks for your reply and Good Luck!!
